### ISSUE TITLE
Massive Lag

### ISSUE THREAD

**Issue by UltraBlackLinux** [Earthcomputer/multiconnect#165]
Hey there,
Multiconnect 1.3.36 seems broken somehow:
![Screenshot_0413_180558](https://user-images.githubusercontent.com/62404294/114584375-e7964a80-9c82-11eb-9f7c-4d000960ee63.png)
Here is my log: https://paste.ee/p/VZAQJ (Are the crashes also caused by multiconnect?)
Also with version 1.3.35 I always get kicked, when using a minecraft version below 1.13, works again with 1.3.34
Are you able to fix this?
Thanks!

**Comment by Earthcomputer** [comment]
![image](https://user-images.githubusercontent.com/13084089/114592465-e2d19680-9c82-11eb-8501-42c14c498074.png)

**Comment by UltraBlackLinux** [comment]
@Earthcomputer bruh sorry, I didn't know, that a rendering mod would affect this. It's literally only lagging so hard, when having multiconnect active below 1.13

**Comment by Earthcomputer** [comment]
Well, you have performance issues with rendering, it's probably caused by a rendering mod.

I'll give you a clue, it's because there are lots of block entities with special block entity renderers on that server, so either some mod is making block entity rendering less performant, or your computer can't handle all the block entities. Either way, multiconnect doesn't touch block entity rendering at all.

As for the diskishness, this is free software. You didn't pay for the mod and you didn't pay for customer service, and you got a high-quality mod and someone who actually told you the issue when you asked. I wouldn't complain.

**Comment by UltraBlackLinux** [comment]
Anyways, I just hand to update starlight.

**Comment by Earthcomputer** [comment]
Glad you solved it :+1:
