### ISSUE TITLE
Fishing bobber is invisible

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#47]

**Comment by Jordin** [comment]
The fishing bobber is invisible because the entity type is removed from the registry [here](https://github.com/Earthcomputer/multiconnect/blob/master/src/main/java/net/earthcomputer/multiconnect/protocols/v1_12_2/Entities_1_12_2.java#L14) and is not re-added it to the registry. This entity was likely missed since it has the same id as a pig and is one of the ones spawned from a EntitySpawnS2CPacket instead of a MobSpawnS2CPacket.

**Comment by Earthcomputer** [comment]
What the heck, the fishing hook entity was not in `EntityList` in 1.12. Are there any other such entities I should be aware of?
