### ISSUE TITLE
Crashing when opening inventory in singleplayer (tested on Fabric and Quilt)

### ISSUE THREAD

**Issue by Onako2** [Earthcomputer/multiconnect#509]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When opening the inventory with multiconnect installed in singleplayer it crashed. 

**Hardware**
> Surface Pro 8 Business Edition
> CPU: Intel i7
> GPI: Intel Iris
> RAM: 16 GB (4GiB allocated)
> SSD Storage: 256 GB

### Log File

https://mclo.gs/8gaTzWV

### Crash Report (if applicable)

https://mclo.gs/SWfpIIu

**Comment by JaaiDead** [comment]
Some Problem With Viaversion API

**Comment by JaaiDead** [comment]
maybe occurring sine single player is branded as a server since its run in the client and multiconnect cant distinguish btween server and single-player so 
using the following steps to reproduce

- [ ]Have These Following mods 

1.  Multiconnect[Latest]
2. Justenoughcrashes
3. Fabric
4. Fabric API

- [x] Then Run Minecraft and create a single playerworld in creative open the create menu 

1. Then U should be provide with a stacktrace by the justenoughcrashes mod.

**Comment by D1p4k** [comment]
Same problem here 👋🏼

**Comment by JaaiDead** [comment]
https://bytebin.lucko.me/THMgvI1V5Q

**Comment by Onako2** [comment]
> https://bytebin.lucko.me/THMgvI1V5Q

Didn't know you use Hacks publicly on Github XD

**Comment by JaaiDead** [comment]
im confused
