### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by CamperSamu** [Earthcomputer/multiconnect#67]

**Comment by Earthcomputer** [comment]
Sodium and Phosphor are already supported, if you any specific crashes/problems with them please report them. I have already stated why lithium is not supported.

**Comment by CDAGaming** [comment]
Reopened due to a mixin crash indeed existing with Sodium with MixinBlockColors. The attempted fix was noted in https://gitlab.com/CDAGaming/Sodium/-/commit/322b8743f69f80d02dc2ab737a4d23737bd63aaa but was rejected:

https://cdn.discordapp.com/attachments/672270296438407178/726489165264584845/Screenshot_20200627-102806_Discord.jpg

**Comment by Earthcomputer** [comment]
Just so you know, it's in my interest to be compatible with Sodium, as I want to see OptiFine gone. The crash is Sodium's fault, but I think it's going to have to be multiconnect that works around it.

**Comment by CDAGaming** [comment]
Agreed, as at the time of writing, Shaders is the main critical component that separates Optifine and Sodium, and stuff like CIT (Though perhaps a new standalone mod for that could be in order one day).

**Comment by Earthcomputer** [comment]
Someone needs to write a decent shaders mod for Fabric. But anyway we're getting off topic :P

**Comment by CDAGaming** [comment]
Yea haha, that's a journey for another time xD

**Comment by CDAGaming** [comment]
https://github.com/jellysquid3/sodium-fabric/commit/ca188218116ae354d98cfbe36da137108573754e has Resolved this issue, any further conflicts should be reported in a new issue
