### ISSUE TITLE
Joining Subserver as 1.13.2 Kicks for Invalid Payload REGISTER

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/multiconnect#81]
Using Only Multiconnect, no other mods.
Joining gommehd.net (viaversion 1.8-1.16 server) as 1.13.2, then joining the citybuild subserver (1.13.2/1.14.? only) kicks back to lobby. The server sends the message "Invalid Payload REGISTER!"

**Comment by leumasme** [comment]
This only seems to happen with Fabric API installed. I had said "no other mods" because i didn't regard fabric api as an actual mod and just as a dependency, didn't know that multiconnect does not depend on it.

**Comment by Username404-59** [comment]
Why are you trying to connect to gommehd if it's 1.8-1.16 compatible?

Anyway I think that sending the logs could help earthcomputer.

**Comment by Earthcomputer** [comment]
So turns out this was https://github.com/FabricMC/fabric/issues/849, which happens with or without multiconnect installed. Basically fabric API is sending a custom payload packet which old versions of Spigot consider to be invalid. However I added a workaround in mutliconnect, by blocking non-vanilla serverbound custom payload packets if the server is not on the same version as the client. This is something which should be done anyway, as clientside mods unknowingly communicating with a server on the wrong version is a recipe for disaster, and this blocking was already implemented in the server-to-client direction. I added an API for clientside mods to bypass this block if they want to explicitly communicate with older servers.
